#!/bin/sh

VERSION=`cat VERSION`

cp *.la ./pkg/tmp/usr/local/lib
cp -P ./.libs/*.a ./pkg/tmp/usr/local/lib
cp -P ./.libs/*.dylib ./pkg/tmp/usr/local/lib
packagemaker --root ./pkg/tmp --id de.ch-werner.sqliteOdbc \
  -v  --version $VERSION --title "SQLite ODBC v-$VERSION" \
  --scripts ./pkg/scripts --resources ./pkg/resources \
  --out sqlite3odbc.pkg
