#!/bin/sh

if [ $# -ne 1 ] ; then
  echo "Error: must pass version id string as arg, e.g. \"0.83\""
  exit 1
fi

packagemaker --root ./pkg/tmp --id de.ch-werner.sqliteOdbc \
  -v  --version 0.85 --title "SQLite ODBC" --scripts ./pkg/scripts \
 --resources ./pkg/resources \
  --out sqlite3odbc.pkg
